name: uploading
on: 
  push:
    branches:
       - master
jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
     - name: checking out
       uses: actions/checkout@v3
     - name: building
       run: mvn clean install
     - name: Upload Artifacts
       uses: actions/upload-artifact@v3
       with:
        name: artifactory
        path: warbuild
      
    
